springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/professional
    username: postgres
    password: postgres

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    default-schema: liquibase
