
CREATE TABLE professional_dev.project_type (
	id int8 NOT NULL,
	name varchar(50) NOT NULL,
	CONSTRAINT project_type_pk PRIMARY KEY (id)
);

CREATE TABLE professional_dev.project (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	project_name varchar(255) NOT NULL,
	"location" varchar(255) NOT NULL,
	nation varchar(255) NOT NULL,
	start_date date NOT NULL,
	project_type_id int8 NOT NULL,
	"size" numeric(8, 2) NULL,
	size_unit varchar(255) NULL,
	status varchar(255) NULL,
	is_visible bool NOT NULL,
	CONSTRAINT project_pkey PRIMARY KEY (id)
);

CREATE TABLE professional_dev.project_detail (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_main bool NOT NULL,
	description varchar(255) NOT NULL,
	project_id int8 NOT NULL,
	CONSTRAINT project_detail_pkey PRIMARY KEY (id)
);


CREATE TABLE professional_dev.project_detail_images (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	project_detail_id int8 NOT NULL,
	image_url varchar(255) NOT NULL,
	"order" int8 NOT NULL,
	CONSTRAINT project_detail_images_pkey PRIMARY KEY (id)
);